### ISSUE TITLE
Schedule SMS: Handling Schedule SMS and back button

### ISSUE THREAD

**Issue by vaishalok** [vinsol/sms-scheduler#4]
Schedule SMS button clicked:
    - case 1: Both fields are filled:
            Schedule SMS
    - case 2: Recipients are selected but no message
            Show an alert dialog with message: "Message is blank."  and with two buttons- 1: Write Message 2: Save as draft
    - case 3: Message is there but no recipients are selected
            Show an alert dialog with message: "No recipients added."   and with two buttons- 1: Add Recipients 2: Save as draft  
    - case 4: Both fields are empty  
            Show an alert dialog with message: "Nothing to schedule"    and with two buttons- 1: Schedule SMS 2: Discard

pressing back: 
    - should create a draft (if any of the fields are filled) + show toast "Message saved as draft"
    - In edit mode if both fields are empty treat it as case 4 of Schedule SMS button

**Comment by achin42** [comment]
working...
